- name: Adding key to rpm_db
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Adding ELK repository
  yum_repository:
    name: elk
    file: elk.repo
    description: ELK Repository
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgcheck: yes

- name: Removing Amzn repository
  shell: /bin/rm -f /etc/yum.repos.d/amzn*

- name: Installing ElasticSearch 
  yum:
    name: elasticsearch
    state: latest
