- name: Copying configuration files to Logstash
  copy: src=/ansible/files/elasticsearch/ dest=/etc/elasticsearch/

- name: Downloading Java 8
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.rpm
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: /home/ec2-user/jdk-8u121-linux-x64.rpm
    validate_certs: False


- name: Installing Java 8
  yum:
    name: /home/ec2-user/jdk-8u121-linux-x64.rpm
    state: present
  environment:
    JAVA_HOME: /usr/java/latest

- name: Starting  ElasticSearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
