- name: Adding key to rpm_db
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Adding ELK repository
  yum_repository:
    name: elk
    file: elk.repo
    description: ELK Repository
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgcheck: yes

- name: Installing Kibana 
  yum:
    name: kibana
    state: latest
