- name: Copying configuration files to Logstash
  copy: src=/ansible/files/logstash/conf.d/ dest=/etc/logstash/conf.d/
  copy: src=/ansible/files/logstash/certs/ dest=/etc/logstash/certs/

- name: Downloading Java 8
#  command:  'wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.rpm"'
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.rpm
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: /home/ec2-user/jdk-8u121-linux-x64.rpm
    validate_certs: False


- name: Installing Java 8
  yum:
    name: /home/ec2-user/jdk-8u121-linux-x64.rpm
    state: present
  environment:
    JAVA_HOME: /usr/java/latest

- name: Starting Logstash
  systemd:
    name: logstash
    state: started
    enabled: yes
