# Enabling ssl and configuring Filebeat to send the logs to Logstash
logging.level: info
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/
  name: filebeat.log

filebeat.prospectors:

- input_type: log
  paths:
    - /var/log/*.log

output.logstash:
  hosts: ["elk-fender.vcali.com:5044"]
  ssl.certificate_authorities: ["/etc/filebeat/logstash-beats.crt"]
