# Enabling ssl and configuring Filebeat to send the logs to Logstash
filebeat.prospectors:

- input_type: log
  paths:
    - /var/log/*.log

output.logstash:
  hosts: ["elk-fender.vcali.com:5044"]
  ssl.certificate_authorities: ["/etc/filebeat/logstash-beats.crt"]
