- name: Creating security group for Logstash
  ec2_group:
    name: logstash_group
    description: Logstash security group
    vpc_id: "{{ my_vpc_id }}"
    rules:
      - proto: tcp
        from_port: 5044
        to_port: 5044
        cidr_ip: 187.101.86.246/32
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 187.101.86.246/32
    rules_egress:
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip: 10.20.1.0/28

- name: Creating security group for ElasticSearch
  ec2_group:
    name: elasticsearch_group
    description: ElasticSearch security group
    vpc_id: "{{ my_vpc_id }}"
    rules:
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip: 10.20.0.0/20
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 187.101.86.246/32
    # ElasticSearch wasnt supposed to access any app, but I just found a bug where, despite of what the doc says, the group is created with access to everything if no rules_egress is applied. So, Im allowing it to access Kibana's interface (it should be blocked on the kibana_group incoming rules)
    # doc here: http://docs.ansible.com/ansible/ec2_group_module.html
    rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 10.20.2.0/28 

- name: Creating security group for Kibana 
  ec2_group:
    name: kibana_group
    description: Kibana security group
    vpc_id: "{{ my_vpc_id }}"
    rules:
      - proto: tcp
        from_port: 80 
        to_port: 80
        cidr_ip: 187.101.86.246/32
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 187.101.86.246/32
    rules_egress:
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip: 10.20.1.0/28

