- name: Creating security group for Logstash
  ec2_group:
    name: logstash_group
    description: Logstash security group
    vpc_id: "{{ my_vpc_id }}"
    rules:
      - proto: tcp
        from_port: 5044 
        to_port: 5044
        cidr_ip: 187.101.86.246/32
    rules_egress:
    # Defining rules for Logstash to be able to access Elasticsearch
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip: 10.20.1.0/28
