- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  
    - include: deploy_aws/create_vpc.yml
    - include: deploy_aws/create_subnets.yml
    - include: deploy_aws/create_groups.yml
    - include: deploy_aws/create_igw.yml
    - include: deploy_aws/create_routes.yml
    - include: deploy_aws/deploy_ec2.yml
    - include: deploy_aws/gather_ips.yml
