
#    - name: Creating Logstash Instance
#      ec2:
#        key_name: key-vcali-nvirg
#        instance_type: t2.micro
#        image: ami-22ce4934 ## Amazon Linux
#        wait: yes
#        group: logstash
#        count: 1
#        vpc_subnet_id: subnet-29e63245
#        assign_public_ip: yes
