- hosts: group_logstash
  user: ec2-user
  become: true
  vars:
    elasticsearch_private_ip: "{{ lookup('file', 'elasticsearch_private_ip') }}"
  tasks:
    - include: install_elk/logstash_install.yml
    - include: install_elk/logstash_config.yml

- hosts: group_elasticsearch
  user: ec2-user
  become: true
  tasks:
    - include: install_elk/elasticsearch_install.yml
    - include: install_elk/elasticsearch_config.yml

- hosts: group_kibana
  user: ec2-user
  become: true
  tasks:
    - include: install_elk/kibana_install.yml
    - include: install_elk/kibana_config.yml
