- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  
    - include: create_vpc.yml
    - include: create_subnets.yml
    - include: create_groups.yml
    - include: deploy_ec2.yml
