- name: Creating security group for Logstash
  ec2_group:
    name: logstash_group
    description: Logstash security group
    vpc_id: "{{ my_vpc_id }}"
    rules:
      - proto: tcp
        from_port: 5044
        to_port: 5044
        cidr_ip: "{{ my_ip }}/32"
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ my_ip }}/32"
    rules_egress:
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip: 10.20.1.0/28
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443 
        to_port: 443
        cidr_ip: 0.0.0.0/0

- name: Creating security group for ElasticSearch
  ec2_group:
    name: elasticsearch_group
    description: ElasticSearch security group
    vpc_id: "{{ my_vpc_id }}"
    rules:
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip: 10.20.0.0/20
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ my_ip }}/32"
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443 
        to_port: 443
        cidr_ip: 0.0.0.0/0

- name: Creating security group for Kibana 
  ec2_group:
    name: kibana_group
    description: Kibana security group
    vpc_id: "{{ my_vpc_id }}"
    rules:
      - proto: tcp
        from_port: 80 
        to_port: 80
        cidr_ip: "{{ my_ip }}/32"
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ my_ip }}/32"
    rules_egress:
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip: 10.20.1.0/28
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443 
        to_port: 443
        cidr_ip: 0.0.0.0/0
