- name: Gathering public IP of Logstash instance
  ec2_remote_facts:
    filters:
      "tag:Name": Logstash
      instance-state-name: running
  register: logstash_ec2_facts

- name: Recording public IP of Logstash instance
  set_fact:
    logstash_public_ip: "{{ logstash_ec2_facts.instances.0.public_ip_address }}"

- name: Gathering public IP of ElasticSearch instance
  ec2_remote_facts:
    filters:
      "tag:Name": ElasticSearch
      instance-state-name: running
  register: elasticsearch_ec2_facts

- name: Recording public IP of ElasticSearch instance
  set_fact:
    elasticsearch_public_ip: "{{ elasticsearch_ec2_facts.instances.0.public_ip_address }}"

- name: Recording private IP of ElasticSearch instance
  set_fact:
    elasticsearch_private_ip: "{{ elasticsearch_ec2_facts.instances.0.private_ip_address }}"

- copy:
    content: "{{ elasticsearch_private_ip }}"
    dest: /ansible/elasticsearch_private_ip


- name: Gathering public IP of Kibana instance
  ec2_remote_facts:
    filters:
      "tag:Name": Kibana
      instance-state-name: running
  register: kibana_ec2_facts

- name: Recording public IP of Kibana instance
  set_fact:
    kibana_public_ip: "{{ kibana_ec2_facts.instances.0.public_ip_address }}"

- template:
    src: ec2_hosts.yml.jinja2
    dest: "/ansible/ec2_hosts"
